package by.bsuir.diplom.controller.command;

public enum CommandName {
    SIGN_IN, SIGN_UP, GO_TO_SIGN_UP_PAGE, GO_TO_SIGN_IN_PAGE, GO_TO_HOME_PAGE, EN_US, RU_RU, LOGOUT,
    GO_TO_COMPANY_PAGE, FILTER_BY_LOCATION, IMPORT_DATA, EDIT_COMPANY_INFO, GO_TO_EDIT_COMPANY_PAGE, EDIT_STAFF,
    DELETE_COMPANY, EDIT_CAPITAL, EDIT_COEFFICIENTS, EDIT_EXPENSES, GO_TO_INDICATORS_PAGE, GO_TO_CORRELATION_PAGE,
    GO_TO_USERS_PAGE, DELETE_USER, GO_TO_EDIT_USER_PAGE, EDIT_USER, WRONG_REQUEST
}
